source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'
use_frameworks!

target 'Severenity' do
pod 'Alamofire', '~> 4.0'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
end