source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Severenity' do
    pod 'Alamofire'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    pod 'Google'
    pod 'GoogleAnalytics'
    pod 'GoogleCloudMessaging'
    pod 'GGLInstanceID'
    pod 'Firebase'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Realm'
    pod 'RealmSwift'

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end
